# Generated by Django 6.0.5 on 2026-05-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawIngestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=100)),
                ('raw_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='rawingestionrecord',
            name='source',
        ),
        migrations.RemoveField(
            model_name='rawingestionrecord',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='sourceintegration',
            name='tenant',
        ),
    ]
