# Generated by Django 6.0.5 on 2026-05-27 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_rawingestion_remove_rawingestionrecord_source_and_more'),
        ('normalization', '0002_alter_normalizedactivity_raw_record'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RawIngestionRecord',
        ),
        migrations.DeleteModel(
            name='SourceIntegration',
        ),
    ]
