# Generated by Django 6.0.5 on 2026-05-27 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_delete_rawingestionrecord_delete_sourceintegration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawingestion',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.AddField(
            model_name='rawingestion',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rawingestion',
            name='source_type',
            field=models.CharField(choices=[('SAP', 'SAP'), ('UTILITY', 'UTILITY'), ('TRAVEL', 'TRAVEL')], max_length=50),
        ),
        migrations.CreateModel(
            name='NormalizedEmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('normalized_value', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.rawingestion')),
            ],
        ),
    ]
