# Generated by Django 6.0.5 on 2026-05-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0004_rename_created_at_rawingestion_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalizedemission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('FLAGGED', 'FLAGGED')], default='PENDING', max_length=20),
        ),
    ]
