# Generated by Django 6.0.5 on 2026-05-27 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0005_alter_normalizedemission_status'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedemission',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='normalizedemission',
            name='edited_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='normalizedemission',
            name='emission_factor',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='normalizedemission',
            name='emissions_kg_co2e',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='normalizedemission',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='rawingestion',
            name='uploaded_by',
            field=models.CharField(default='system', max_length=255),
        ),
    ]
