# Generated by Django 6.0.5 on 2026-05-27 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_rawingestion_remove_rawingestionrecord_source_and_more'),
        ('normalization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalizedactivity',
            name='raw_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.rawingestion'),
        ),
    ]
