# Generated by Django 6.0.5 on 2026-05-27 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0006_normalizedemission_edited_at_and_more'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewqueue',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.normalizedemission'),
        ),
    ]
